# Generated by Django 5.2.8 on 2026-04-14 14:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do prato')),
                ('tempada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempada')),
                ('preparacion', models.TextField(blank=True, null=True, verbose_name='Preparación')),
                ('fotoUrl', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da foto')),
            ],
        ),
        migrations.CreateModel(
            name='LinaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidade', models.FloatField(verbose_name='Cantidade')),
                ('unidade', models.CharField(choices=[('l', 'Litros'), ('ml', 'Mililitros'), ('g', 'Gramos'), ('kg', 'Quilogramos'), ('unidade', 'Unidade(s)'), ('cucharada', 'Culleres'), ('pizca', 'Pizca'), ('taza', 'Cunca')], max_length=50, verbose_name='Unidade')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recetasapp.ingrediente', verbose_name='Ingrediente')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lina_ingredientes', to='recetasapp.plato', verbose_name='Plato')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data do Menú')),
                ('momento', models.CharField(help_text='Ex: Xantar, Cea...', max_length=100, verbose_name='Momento')),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_menu', to='recetasapp.plato', verbose_name='Plato asignado')),
            ],
            options={
                'verbose_name': 'Entrada do Menú',
                'verbose_name_plural': 'Entradas do Menú',
                'ordering': ['-data'],
            },
        ),
    ]
